### ISSUE TITLE
undefined method 'cards' for Stripe::Customer

### ISSUE THREAD

**Issue by parabuzzle** [sb8244/rspec-stripe#5]
when using `it 'foo', stripe: { customer: :new, card: :visa } do ...`

```
NoMethodError:
            undefined method `cards' for #<Stripe::Customer:0x007fd76cd737c8>
          # /Users/heijmans/.rvm/gems/ruby-2.3.1/gems/stripe-1.43.1/lib/stripe/stripe_object.rb:271:in `method_missing'
          # /Users/heijmans/.rvm/gems/ruby-2.3.1/gems/rspec-stripe-0.0.8/lib/rspec-stripe/factories/card.rb:12:in `get'
          # /Users/heijmans/.rvm/gems/ruby-2.3.1/gems/rspec-stripe-0.0.8/lib/rspec-stripe/factories/card.rb:24:in `cleanup'
          # /Users/heijmans/.rvm/gems/ruby-2.3.1/gems/rspec-stripe-0.0.8/lib/rspec-stripe/runner.rb:18:in `block in cleanup!'
          # /Users/heijmans/.rvm/gems/ruby-2.3.1/gems/rspec-stripe-0.0.8/lib/rspec-stripe/runner.rb:17:in `each'
          # /Users/heijmans/.rvm/gems/ruby-2.3.1/gems/rspec-stripe-0.0.8/lib/rspec-stripe/runner.rb:17:in `cleanup!'
          # /Users/heijmans/.rvm/gems/ruby-2.3.1/gems/rspec-stripe-0.0.8/lib/rspec-stripe/test_frameworks/rspec.rb:33:in `block (2 levels) in configure!'
```

It appears that you're calling `cards` instead of `sources`

**Comment by sb8244** [comment]
Do you know which gem version changed this? Is it backwards compatible with different gem and API versions?

**Comment by parabuzzle** [comment]
The version of the stripe gem I'm using is 1.43.1 (published June 17, 2016)

It appears that the api moved to `sources` over `cards` back in Feb 2015: https://github.com/stripe/stripe-ruby/issues/215

I don't know exactly when they changed the gem to support this and I don't see how `cards` doesn't work by looking at their code. But its officially been `sources` for quite awhile.
